feat: Aave v2 cap adapters for stables
bgd-labs/aave-capo pull request #19
Opened 2024-04-11 17:50 UTC by rustboyar

Price cap adapters for stablecoins on Aave V2.

2024-04-16 13:48 UTC, kyzia551 commented on tests/AaveV2/EthereumV2Test.t.sol
> +
```suggestion
```

2024-04-17 10:04 UTC, kyzia551 approved these changes
Don't forget to put about DPI on readme

2024-04-17 11:21 UTC, sakulstra requested changes
looks good to me, but please include a diff snapshot on the tests.
Last time we only noticed a misconfiguration **after** deployment, because on diff-snapshot the price changed unintendedly. Better this time we check before deployment.

2024-04-17 11:21 UTC, sakulstra commented on scripts/AaveV2/DeployEthereum.s.sol
> +    adapters.usdtAdapter = GovV3Helpers.deployDeterministic(
It's fine, but a bit weird to use `GovV3Helpers.deployDeterministic` here - it's just a wrapper around create2utils with a static salt.

2024-04-17 12:26 UTC, sakulstra approved these changes

2024-04-18 08:29 UTC, merged